spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0
      default-hostname: localhost
      default-ip-address: 127.0.0.1

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    ip-address: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF